sym1 = "SCHA"
sym2 = "SPY"
#referencforecast()
x1 = setup(sym1)
x2 = setup(sym2)
save(x1, file=paste0("~/data/equity/",sym1,"1.Rdata"))
save(x2, file=paste0("~/data/equity/",sym2,"1.Rdata"))
total = merge(x1,x2, by.x = "date", by.y = "date", all = FALSE, sort = TRUE)
xy = total
detach(total)
attach(total)
names(total)
print(paste("x:", sym1, "        y:", sym2))
model1=lm(dailyhigh.x ~  lag1(log(close.x)) + lag1(dailychange.x)  + lag1(diff1(dailychange.x))+ lag1(weeklychange.x)  + lag1(monthlychange.x)
          + lag1(dailychange.x - dailychange.y) 
          , data= total); print(summary(model1))
model2=lm(dailyhigh.x ~  lag1(log(close.x)) + lag1(dailychange.x)  + lag1(diff1(dailychange.x))+ lag1(weeklychange.x)  + lag1(monthlychange.x)
          + lag1(dailychange.x - dailychange.y) 
          + lag1(high5.x/close.x)+ lag1(low5.x/close.x)
          , data= total); print(summary(model2))
model2=lm(dailyhigh.x ~  lag1(log(close.x))
          + lag1(diff1(dailychange.x))+ lag1(weeklychange.x)  + lag1(monthlychange.x)
          + lag1(dailychange.x - dailychange.y) 
          + lag1(high5.x/close.x)+ lag1(low5.x/close.x)
          + lag1(dailychange.x < -.00) 
          , data= total); print(summary(model2))
model3=lm (dailychange.x < .00~ lag1(dailychange.x > 00), data = total); print(summary(model3))
#+ lag1(dailychange.x)  
#+ lag1(dailylow.x) + lag1(dailyhigh.x)
#+ lag1(dailychange.y > 0)
tail(high5.x/close.x)
summary(lm(low5.x/close.x ~I(high5.x/close.x)))
plot(((high5.x/close.x* low5.x/close.x) ))
plot(high5.x- low5.x)
plot(high5.x, low5.x)
plot(high5.x/close.x)
#+ lag1((close.x - high5.x)/ high5.x) +lag1((close.x - low5.x)/ low5.x)

#+ lag1(dailyvol.x / dailyvol.y)
#+ lag1((close.x - high21.x)/ high21.x) +lag1((close.x - low21.x)/ low21.x)
#lag1(log(close.x)) +
#+ lag1(weeklychange.x - weeklychange.y)
#+ dailychange.y + dailylow.y + dailyhigh.y
#+lag1(diff5_1(weeklychange.x))
tail((close.x - low5.x)/ low5.x)
lag1((close.x - high5.x)/ high5.x)
modelx=lm(dailychange.x ~ dailychange.y, data= xy); print(summary(modelx))
modelweek=lm(weeklychange.x ~ weeklychange.y, data= xy); print(summary(modelweek))
modelmonth=lm(monthlychange.x ~ monthlychange.y, data= xy); print(summary(modelmonth))
modelyear=lm(annualchange.x ~ annualchange.y, data= xy); print(summary(modelyear))
modelx=lm(dailyhigh.x ~ lag1(dailychange.x) + (dailychange.y), data= xy); print(summary(modelx))
#+ dailylow.y + dailyhigh.y + date
#  modely=lm(dailychange.y ~ dailychange.x, data= xy); print(summary(modely))
#  modelnew = step(model1)
#  print(summary(modelnew))
print(paste(sym1,"vs", sym2))
diffmodel=lm(dailychange.x - dailychange.y ~ lag1(dailychange.x -dailychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(weeklychange.x - weeklychange.y ~ lag5(weeklychange.x -weeklychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(monthlychange.x - monthlychange.y ~ lag21(monthlychange.x -monthlychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(twomonthchange.x - twomonthchange.y ~ lag42(twomonthchange.x -twomonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(threemonthchange.x - threemonthchange.y ~ lag63(threemonthchange.x -threemonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(sixmonthchange.x - sixmonthchange.y ~ lag126(sixmonthchange.x -sixmonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(annualchange.x - annualchange.y ~ lag252(annualchange.x -annualchange.y), data= xy); print(summary(diffmodel))
#twomonthchange
diffmodel=lm(dailychange.x - dailychange.y ~ lag1(dailychange.x -dailychange.y) + lag1(dailychange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(weeklychange.x - weeklychange.y ~ lag5(weeklychange.x -weeklychange.y) + lag5(weeklychange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(monthlychange.x - monthlychange.y ~ lag21(monthlychange.x -monthlychange.y) + lag21(monthlychange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(twomonthchange.x - twomonthchange.y ~ lag42(twomonthchange.x -twomonthchange.y) + lag42(twomonthchange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(threemonthchange.x - threemonthchange.y ~ lag63(threemonthchange.x -threemonthchange.y) + lag63(threemonthchange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(sixmonthchange.x - sixmonthchange.y ~ lag126(sixmonthchange.x -sixmonthchange.y) + lag126(sixmonthchange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(annualchange.x - annualchange.y ~ lag252(annualchange.x -annualchange.y) + lag252(annualchange.x), data= xy); print(summary(diffmodel))

diffmodel=lm(dailychange.x  ~ lag1(dailychange.x -dailychange.y) + lag1(dailychange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(weeklychange.x  ~ lag5(weeklychange.x -weeklychange.y) + lag5(weeklychange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(monthlychange.x  ~ lag21(monthlychange.x -monthlychange.y) + lag21(monthlychange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(twomonthchange.x ~ lag42(twomonthchange.x -twomonthchange.y) + lag42(twomonthchange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(threemonthchange.x ~ lag63(threemonthchange.x -threemonthchange.y) + lag63(threemonthchange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(sixmonthchange.x  ~ lag126(sixmonthchange.x -sixmonthchange.y) + lag126(sixmonthchange.x), data= xy); print(summary(diffmodel))
diffmodel=lm(annualchange.x  ~ lag252(annualchange.x -annualchange.y) + lag252(annualchange.x), data= xy); print(summary(diffmodel))

diffmodel=lm(dailychange.x ~ lag1(dailychange.x -dailychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(weeklychange.x ~ lag5(weeklychange.x -weeklychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(monthlychange.x ~ lag21(monthlychange.x -monthlychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(twomonthchange.x ~ lag42(twomonthchange.x -twomonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(threemonthchange.x ~ lag63(threemonthchange.x -threemonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(sixmonthchange.x ~ lag126(sixmonthchange.x -sixmonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(annualchange.x ~ lag252(annualchange.x -annualchange.y), data= xy); print(summary(diffmodel))

diffmodel=lm(dailychange.x ~ lag1(dailychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(weeklychange.x ~ lag5(weeklychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(monthlychange.x ~ lag21(monthlychange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(twomonthchange.x ~ lag42(twomonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(threemonthchange.x ~ lag63(threemonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(sixmonthchange.x ~ lag126(sixmonthchange.y), data= xy); print(summary(diffmodel))
diffmodel=lm(annualchange.x ~ lag252(annualchange.y) + annualchange.y, data= xy); print(summary(diffmodel))
