+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
+ lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
print(c(k, fit1[k]), rsq[k])
k = 1
trials = 20
rsq = rep(NA, trials)
#(as.character(formula1))[[3]]
estimate = matrix (NA, trials,length(all.vars(formula)) +1)
stderror = matrix (NA, trials,length(all.vars(formula)) +1)
tvalue = matrix (NA, trials,length(all.vars(formula)) +1)
pvalue = matrix (NA, trials,length(all.vars(formula)) +1)
sigma= rep (NA, trials)
sds = rep (NA, trials)
resid  =rep (NA, trials)
fit2 = fit1  = rep(NA, trials)
scaled = rep(NA, trials)
#100,length(all.vars(formula)) +1)
#end =  0
#for (i in 1:5) {
#loop
start =  1
end = trials
for (k in seq(start,end,1)) {
lagk = make.lag(k)
model=lm(bigform, data= x1);
drop1(model)
print(summary(model))
print(k)
rsq[k] = summary(model)$r.squared
sigma[k] = summary(model)$sigma
sds [k] = sd(periodchange(k), na.rm = TRUE)
#resid[k] = summary(model)$resid
#summary(model)$
estimate [k,] = (summary(model)$coefficients[,1])
stderror [k,] = (summary(model)$coefficients[,2])
tvalue[k,] = (summary(model)$coefficients[,3])
pvalue[k,] = (summary(model)$coefficients[,4])
#    fit1[k] = tail(timefit(model), 1)
fit1[k] = tail(generalfit(model),1)
scaled[k] = fit1[k]/ k
#    fitcheck = timefit(model)
fitcheck = generalfit(model)
print(c(k, fit1[k]), rsq[k])
#plot(fitcheck)
#lines(fitted(model), col = k)
#    title(main = paste("k", k))
#    plot(c(tail(fitcheck, 200+k)))
#    title(main = paste("k =" ,k))
#    lines(c(tail(offset(model), 200)), col = 'red')
#    lines(tail(periodhigh(k), 200), col = "green")
#    lines(tail(periodchange(k), 200, col = "black"))
#    lines(tail(periodlow(k), 200, col = "red"))
}
#return(list(rsq, sigma, sds, estimate, stderror, tvalue, pvalue, fit1, scaled, fitcheck))
par(mfrow =c(2,1))
plot(rsq[1:k], ylab = "Percentage of variation explained", xlab = "length of holding period k")
title (main = list(paste("Model to explain", as.character(formula)[[2]])), sym1)
plot (sds, ylab = "total s.d and model sigma", xlab = "length of holding period k")
lines (sigma, col = "blue")
lines(rsq[1:k], col = 'red')
names(formula)
names(formula1)
as.character(formula1)
plot(hightohigh, dailychange)
plot(lowtolow, dailychange)
summary(dailychange ~lowtolow)
summary(lm(dailychange ~lowtolow))
summary(lm(dailyhigh ~lowtolow))
summary(lm(dailylow ~lowtolow))
summary(lm(cbind(dailyhigh, dailylow, dailychange ~lowtolow))
)
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~lowtolow))
summary(lm(cbind(dailyhigh, dailylow, dailychange ~lag1(lowtolow))
)
)
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~lag1(lowtolow)))
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~ cbind(lag1(lowtolow), lag1(hightohigh))))
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~ lag1(lowtolow) + lag1(hightohigh)))
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~ lag1(hightohigh)))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh)))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh) + lag1(lowtolow) + lag1(dailychange) )))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh) + lag1(lowtolow) + lag1(dailychange) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh) + lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(hightohigh) + lag1(lowtolow)  ))
step(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(hightohigh) + lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(hightohigh) + lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(lowtolow) + lag2(lowtolow) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow) + lag1(weeklyhigh) ))
plot(lag1(hightohigh), dailychange)
plot(lag1(hightohigh), dailyhigh)
plot(lag1(lowtolow), dailyhigh)
plot(lag1(lowtolow), lowtolow)
plot(lag1(hightohigh), hightohigh)
savehistory("~/program/equityproject/history.R")
sapply(x1,FUN=function(x) {plot(lag1(x), x)})
par(mfcol=c(1,1))
sapply(x1,FUN=function(x) {plot(lag1(x), x)})
me = sapply(x1,FUN=function(x) {plot(lag1(x), x); title(main="hello world")})
me
names(me)
me2 = sapply(x1,FUN=function(x) {plot(lag1(x), x); title(main=names(me))})
me2
names(x1)
for (names in names(x1))
{plot(lag1(x), x); title(name))}
for (names in names(x1))
{plot(lag1(x), x); title(name)}
{plot(lag1(x1$name), x); title(name)}
for (names in names(x1))
{plot(lag1(eval(parse(text =name))), eval(parse(text =name))); title(name)}
)
par(mfcol=c(5,5))
for (names in names(x1))
{plot(lag1(eval(parse(text =name))), eval(parse(text =name))); title(name)}
me = sapply(x1,FUN=function(x) {plot(lag1(x), x); title(main="hello world")})
names(x1)[1]
i = 1
me = sapply(x1,FUN=function(x) {plot(lag1(x), x); i = i+ 1;title(main=names(x1)[1])})
par(mfcol=c(3,3))
i = 1
me = sapply(x1,FUN=function(x) {plot(lag1(x), x); i = i+ 1;title(main=names(x1)[i])})
names(x1)[2]
??apply
me = apply(x1,2, FUN=function(x) {plot(lag1(x), x);})
me = apply(x1,2, FUN=function(x) {
summary(lm(lag1(x), x)))
}
me = apply(x1,2, FUN=function(x) {
summary(lm(lag1(x), x))
}
)
me = apply(x1,2, FUN=function(x) {summary(lm(lag1(x), x))})
me = apply(x1,2, FUN=function(x) {summary(lm((x)~ lag1(x)))})
me = apply(x1,2, FUN=function(x) {summary(lm((x)~ lag1(x)))})
lag1
source('~/program/getdata.r')
source('~/program/getdata.r')
lag1
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow) + lag1(weeklyhigh) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow) + lag1(weeklyhigh) + lag2(weeklyhigh) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag1(lowtolow ^2) + lag1(weeklyhigh) + lag2(weeklyhigh) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow^2) + lag1(weeklyhigh) + lag2(weeklyhigh) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag1(lowtolow^2) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh^3) + lag1(lowtolow) + lag1(lowtolow^2) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh^2) + lag1(lowtolow) + lag1(lowtolow^2) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailychange^2) + lag1(lowtolow) + lag1(lowtolow^2) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh^2) + lag1(lowtolow) + lag1(lowtolow^2) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh^2) + lag1(lowtolow) + lag1(lowtolow^2)+ lag1(lowtolow+1) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
lowtolow +1
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~
lag1(dailyhigh^2)
#+ lag1(lowtolow)
+ lag1(lowtolow^2)
+ lag1(lowtolow+1) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~
lag1(dailyhigh^2)
+ lag1(lowtolow)
+ lag1(lowtolow^2)
+ lag1(hightohigh)
+ lag1(hightohigh^2)
+ lag1(lowtolow+1) + lag1(weeklyhigh) + lag1(weeklyhigh^2) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~
lag1(dailyhigh^2)
+ lag1(lowtolow)
+ lag1(lowtolow^2)
+ lag1(hightohigh)
+ lag1(hightohigh^2)
+ lag1(lowtolow^3)
)
)
model1 = (lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~
lag1(dailyhigh^2)
+ lag1(lowtolow)
+ lag1(lowtolow^2)
+ lag1(hightohigh)
+ lag1(hightohigh^2)
+ lag1(lowtolow^3)
+ lag1(weeklyhigh) + lag1(weeklyhigh^2) )
)
generalfit(model)
source('~/program/getdata.r')
generalfit(model)
lagk
lagk = make.lag(k)
model1 = (lm(cbind(dailyhigh) ~
lagk(dailyhigh^2)
+ lagk(lowtolow)
+ lagk(lowtolow^2)
+ lagk(hightohigh)
+ lagk(hightohigh^2)
+ lagk(lowtolow^3)
+ lagk(weeklyhigh) + lagk(weeklyhigh^2) )
)
generalfit(model)
generalfit(model1)
tail(generalfit(model1))
names(model1$coefficients)
eval(parse(text =names(model$coefficients[2])
)
)
(model1$coefficients)
dim(model1$coefficients)
nrow(model1$coefficients)
ncol(model1$coefficients)
length(model1$coefficients)
length(model1$coefficients) * eval(parse(text =names(model$coefficients))
)
(model1$coefficients) * eval(parse(text =names(model$coefficients)))
eval(parse(text =names(model$coefficients)))
x4 = eval(parse(text =names(model$coefficients)))
x4 * model1$coefficients
dim(x4)
nrow(x4)
length(x4)
str(x4)
tail(x4)
tail(x1)
model1 = (lm(cbind(dailyhigh) ~
#lagk(dailyhigh^2)
+ lagk(lowtolow)
#+ lagk(lowtolow^2)
+ lagk(hightohigh)
# + lagk(hightohigh^2)
# + lagk(lowtolow^3)
+ lagk(weeklyhigh)
#+ lagk(weeklyhigh^2)
)
model1 = (lm(cbind(dailyhigh)) ~
model1 = (lm(cbind(dailyhigh)) ~
#lagk(dailyhigh^2)
+ lagk(lowtolow)
#+ lagk(lowtolow^2)
+ lagk(hightohigh)
# + lagk(hightohigh^2)
# + lagk(lowtolow^3)
+ lagk(weeklyhigh)
#+ lagk(weeklyhigh^2)
)
)
tail(generalfit(model1))
model1 = (lm(dailyhigh) ~
#lagk(dailyhigh^2)
+ lagk(lowtolow)
model1 = (lm(dailyhigh) ~
#lagk(dailyhigh^2)
+ lagk(lowtolow)
#+ lagk(lowtolow^2)
+ lagk(hightohigh)
# + lagk(hightohigh^2)
# + lagk(lowtolow^3)
+ lagk(weeklyhigh)
#+ lagk(weeklyhigh^2)
)
)
tail(generalfit(model1))
(model1$coefficients)
tail(generalfit(model1))
tail(generalfit(model1))
model1 = (lm(dailyhigh) ~
#lagk(dailyhigh^2)
lagk(lowtolow)
#+ lagk(lowtolow^2)
model1 = (lm(dailyhigh) ~
#lagk(dailyhigh^2)
lagk(lowtolow)
#+ lagk(lowtolow^2)
+ lagk(hightohigh)
# + lagk(hightohigh^2)
# + lagk(lowtolow^3)
+ lagk(weeklyhigh)
#+ lagk(weeklyhigh^2)
)
tail(generalfit(model1))
)
model1 = (lm(dailyhigh ~lagk(lowtolow) + lagk(hightohigh)+ lagk(weeklyhigh)
)
)
model1 = (lm(dailyhigh ~lagk(lowtolow) + lagk(hightohigh)+ lagk(weeklyhigh)
model1 = (lm(dailyhigh ~lagk(lowtolow) + lagk(hightohigh)+ lagk(weeklyhigh) )
Q
model1 = (lm(dailyhigh ~lagk(lowtolow) + lagk(hightohigh)+ lagk(weeklyhigh) )
)
summary(model1)
tail(generalfit(model1))
(generalfit(model1))
k
k =1
model1 = lm(dailyhigh ~lagk(lowtolow) + lagk(hightohigh)+ lagk(weeklyhigh) )
#lagk(dailyhigh^2)
#+ lagk(lowtolow^2)
# + lagk(hightohigh^2)
# + lagk(lowtolow^3)
+ lagk(weeklyhigh)
#+ lagk(weeklyhigh^2)
)
summary(model1)
generalfit(model1)
model = lm(dailyhigh ~lagk(lowtolow) + lagk(hightohigh)+ lagk(weeklyhigh) )
summary(model)
total = 0
Intercept  = 1
#total = model$coefficients[i] * Intercept
lag1 = lagk = nolag
for (i in 1:17){
total = total + model$coefficients[i] * eval(parse(text =names(model$coefficients[i])))
}
total
model$coefficients[i]
total = total + model$coefficients[1] * eval(parse(text =names(model$coefficients[i])))
model$coefficients[1]
total = total + model$coefficients[2] * eval(parse(text =names(model$coefficients[i])))
print(i)
for (i in 1:17){
print(i)
total = total + model$coefficients[2] * eval(parse(text =names(model$coefficients[i])))
}
for (i in 1:17){
print(i)
total = total + model$coefficients[2] * eval(parse(text =names(model$coefficients[i])))
head(total)
}
for (i in 1:17){
print(i)
total = total + model$coefficients[2] * eval(parse(text =names(model$coefficients[i])))
print(head(total))
}
eval(parse(text =names(model$coefficients[2])))
total + model$coefficients[2]
total + model$coefficients[3]
model
model$coefficients[1]
for (i in 1:length(model$coefficients)){
print(i)
total = total + model$coefficients[1] * eval(parse(text =names(model$coefficients[2])))
print(tail(total))
}
for (i in 1:length(model$coefficients)){
print(i)
total = total + model$coefficients[i] * eval(parse(text =names(model$coefficients[i])))
}
total
attach(x1)
generalfit(model1)
lowtolow^(1:4)
model
length(model$coefficients)
length(lowmodel$coefficients)
plot(lag1(hightohigh), dailychange)
plot(lag1(hightohigh), dailychange)
plot(lag1(hightohigh), dailyhigh)
plot(lag1(lowtolow), dailyhigh)
plot(lag1(lowtolow), lowtolow)
plot(lag1(hightohigh), hightohigh)
source('~/program/getdata.r')
plot(lag1(hightohigh), dailychange)
plot(lag1(hightohigh), dailyhigh)
plot(lag1(lowtolow), dailyhigh)
plot(lag1(lowtolow), lowtolow)
plot(lag1(hightohigh), hightohigh)
plot(lag1(hightohigh^2), hightohigh)
plot(lag1((hightohigh+1)^2), hightohigh)
plot(lag1((hightohigh+1)^4), hightohigh)
plot(lag1((hightohigh+1)^3), hightohigh)
plot(lag1((hightohigh+1)), hightohigh)
plot(lag1(log(hightohigh+1)), hightohigh)
plot(lag1(lowtolow), lowtolow)
plot(lag1(lowtolow), dailyhigh)
plot(lag1(lowtolow), lowtolow)
plot(lag1(hightohigh), dailychange)
plot(lag1(dailyhigh), dailychange)
plot(lag1(lowtolow), dailyhigh)
plot(lag1(weeklyhigh), dailychange)
plot(lag1(lowtoclose), dailychange)
plot(lag1(lowclose), dailychange)
plot(lag1(downclose), dailychange)
plot(lag1(downclose), lowtolow)
plot(lag1(upclose), lowtolow)
plot(lag1(uptoclose), lowtolow)
plot(lag1(uptoclose), hightohigh)
plot(lag1(uptoclose), dailychange)
plot(lag1(uptoclose), dailyhigh)
plot(dailyhigh~ lag1(uptoclose) )
summary(lm(dailyhigh~ lag1(uptoclose) ))
summary(lm(dailyhigh~ lag1(downclose) ))
summary(lm(dailylow~ lag1(downclose) ))
summary(lm(downclose~ lag1(downclose) ))
plot(lm(downclose~ lag1(downclose) ))
plot((downclose~ lag1(downclose) ))
summary(lm(dailylow~ lag1(downclose) ))
summary(lm(dailyhigh~ lag1(downclose) ))
summary(lm(dailyhigh~ lag1(downclose) lag2(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose)))
summary(lm(dailychange~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + lag7(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9)))
summary(lm(hightohigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9)))
summary(lm(hightohigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9)))
summary(lm(downclose~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose)))
summary(lm(dailyhigh~ lag1(uptoclose) +lag2(uptoclose) + lag3(uptoclose) + lag4(uptoclose) + lag5(uptoclose) + lag6(uptoclose) + mylag(uptoclose,7) + mylag(uptoclose,8) + mylag(uptoclose,9) + lag10(uptoclose)))
summary(lm(dailyhigh~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose)
+lag2(uptoclose) + lag3(uptoclose) + lag4(uptoclose) + lag5(uptoclose) + lag6(uptoclose) + mylag(uptoclose,7) + mylag(uptoclose,8) + mylag(uptoclose,9) + lag10(uptoclose)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose)))
summary(lm(dailyhigh~ lag1(uptoclose) +lag2(uptoclose) + lag3(uptoclose) + lag4(uptoclose) + lag5(uptoclose) + lag6(uptoclose) + mylag(uptoclose,7) + mylag(uptoclose,8) + mylag(uptoclose,9) + lag10(uptoclose)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose) + lag1(dailychange)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose) + lag1(dailyhigh)))
summary(lm(dailylow~ lag1(downclose) +lag2(downclose) + lag3(downclose) + lag4(downclose) + lag5(downclose) + lag6(downclose) + mylag(downclose,7) + mylag(downclose,8) + mylag(downclose,9) + lag10(downclose) + lag1(dailychange) + lag1(log(volume)))
)
summary(lm(dailyhigh~ lag1(uptoclose) +lag2(uptoclose) + lag3(uptoclose) + lag4(uptoclose) + lag5(uptoclose) + lag6(uptoclose) + mylag(uptoclose,7) + mylag(uptoclose,8) + mylag(uptoclose,9) + lag10(uptoclose)))
savehistory("~/program/equityproject/happyday.R")
