#    lines(tail(periodhigh(k), 200), col = "green")
#    lines(tail(periodchange(k), 200, col = "black"))
#    lines(tail(periodlow(k), 200, col = "red"))
}
k = 1
model=lm(bigform, data= x1);
lagk = make.lag(k)
model=lm(bigform, data= x1);
step(model)
model=lm(bigform, data= x1);
step(model)
print(summary(model))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
+ lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
+ lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
model=lm(bigform, data= x1);
step(model)
drop1(model)
print(summary(model))
print(k)
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
+ lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(model))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(model))
print(summary(lm(bigformula)))
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
#                         + lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
+ lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
+ lagk(threemonthchange)
+ lagk(sixmonthchange)
+ lagk(ninemonthchange)
+ lagk(annualchange)
+ lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
#                        +  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
+ lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
+ lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodayhigh)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
+ lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
formula = bigform  <- (periodhigh(k) ~
#                         lagk(dailyhigh - lag1(dailyhigh)) +
lagk(lowtolow)  +
+  lagk(hightohigh)
+ lagk(weeklychange)
+ lagk(weeklyhigh)
#                        + lagk(weeklylow)
+  lagk(twodaychange)
+ lagk(log(close))
#                        + lagk(log(volume))
+ lagk(close)
+ lagk(dailyhigh)
+ lagk(dailylow)
+ lagk(monthlyhigh)
+ lagk(monthlylow)
+ lagk(weeklychange)
+ lagk(monthlychange)
#                        + lagk(twomonthchange)
#                        + lagk(threemonthchange)
#                        + lagk(sixmonthchange)
#                        + lagk(ninemonthchange)
#                        + lagk(annualchange)
#                        + lagk(twoyearchange)
)
print(summary(lm(bigform)))
print(c(k, fit1[k]), rsq[k])
k = 1
trials = 20
rsq = rep(NA, trials)
#(as.character(formula1))[[3]]
estimate = matrix (NA, trials,length(all.vars(formula)) +1)
stderror = matrix (NA, trials,length(all.vars(formula)) +1)
tvalue = matrix (NA, trials,length(all.vars(formula)) +1)
pvalue = matrix (NA, trials,length(all.vars(formula)) +1)
sigma= rep (NA, trials)
sds = rep (NA, trials)
resid  =rep (NA, trials)
fit2 = fit1  = rep(NA, trials)
scaled = rep(NA, trials)
#100,length(all.vars(formula)) +1)
#end =  0
#for (i in 1:5) {
#loop
start =  1
end = trials
for (k in seq(start,end,1)) {
lagk = make.lag(k)
model=lm(bigform, data= x1);
drop1(model)
print(summary(model))
print(k)
rsq[k] = summary(model)$r.squared
sigma[k] = summary(model)$sigma
sds [k] = sd(periodchange(k), na.rm = TRUE)
#resid[k] = summary(model)$resid
#summary(model)$
estimate [k,] = (summary(model)$coefficients[,1])
stderror [k,] = (summary(model)$coefficients[,2])
tvalue[k,] = (summary(model)$coefficients[,3])
pvalue[k,] = (summary(model)$coefficients[,4])
#    fit1[k] = tail(timefit(model), 1)
fit1[k] = tail(generalfit(model),1)
scaled[k] = fit1[k]/ k
#    fitcheck = timefit(model)
fitcheck = generalfit(model)
print(c(k, fit1[k]), rsq[k])
#plot(fitcheck)
#lines(fitted(model), col = k)
#    title(main = paste("k", k))
#    plot(c(tail(fitcheck, 200+k)))
#    title(main = paste("k =" ,k))
#    lines(c(tail(offset(model), 200)), col = 'red')
#    lines(tail(periodhigh(k), 200), col = "green")
#    lines(tail(periodchange(k), 200, col = "black"))
#    lines(tail(periodlow(k), 200, col = "red"))
}
#return(list(rsq, sigma, sds, estimate, stderror, tvalue, pvalue, fit1, scaled, fitcheck))
par(mfrow =c(2,1))
plot(rsq[1:k], ylab = "Percentage of variation explained", xlab = "length of holding period k")
title (main = list(paste("Model to explain", as.character(formula)[[2]])), sym1)
plot (sds, ylab = "total s.d and model sigma", xlab = "length of holding period k")
lines (sigma, col = "blue")
lines(rsq[1:k], col = 'red')
names(formula)
names(formula1)
as.character(formula1)
plot(hightohigh, dailychange)
plot(lowtolow, dailychange)
summary(dailychange ~lowtolow)
summary(lm(dailychange ~lowtolow))
summary(lm(dailyhigh ~lowtolow))
summary(lm(dailylow ~lowtolow))
summary(lm(cbind(dailyhigh, dailylow, dailychange ~lowtolow))
)
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~lowtolow))
summary(lm(cbind(dailyhigh, dailylow, dailychange ~lag1(lowtolow))
)
)
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~lag1(lowtolow)))
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~ cbind(lag1(lowtolow), lag1(hightohigh))))
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~ lag1(lowtolow) + lag1(hightohigh)))
summary(lm(cbind(dailyhigh, dailylow, dailychange) ~ lag1(hightohigh)))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh)))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh) + lag1(lowtolow) + lag1(dailychange) )))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh) + lag1(lowtolow) + lag1(dailychange) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh) ~ lag1(hightohigh) + lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(hightohigh) + lag1(lowtolow)  ))
step(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(hightohigh) + lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(hightohigh) + lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(lowtolow)  ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(lowtolow) + lag2(lowtolow) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow) ))
summary(lm(cbind(dailyhigh, dailylow, dailychange, hightohigh, lowtolow) ~ lag1(dailyhigh) + lag1(lowtolow) + lag2(lowtolow) + lag1(weeklyhigh) ))
plot(lag1(hightohigh), dailychange)
plot(lag1(hightohigh), dailyhigh)
plot(lag1(lowtolow), dailyhigh)
plot(lag1(lowtolow), lowtolow)
plot(lag1(hightohigh), hightohigh)
savehistory("~/program/equityproject/history.R")
