source('getdata.r')
source('~/program/equityproject/getdata.r')
#install.packages("lattice")
install.packages("ggplot2")
library(ggplot2)
library(lattice)
sym1 = "SCHA"
sym2 = "SCHB"
scha = x1 = setup(sym1)
schb = x2 = setup(sym2)
fndx = init("FNDX")
fndx  = addvariables(fndx)
fnda = setup("FNDA")
schm  = setup("SCHM")
schz  = setup("SCHZ")
schf = setup("SCHF")
x = fndx
detach(x1)
attach(x1)
plot(dailyhigh, dailylow)

xyplot(dailyhigh[dailyvol<.03] ~dailylow[dailyvol<.03])
qplot(dailylow[dailyvol<.03],dailyhigh[dailyvol<.03] )
m = lm(dailyhigh[dailyvol<.015] ~lag1(dailylow[dailyvol<.015]))
summary(volmodel  <- lm (dailyvol~ lag1(dailyvol) 
             + lag1(monthlychange)
            , data = x1))
+ lag2(dailyvol) 

tail(generalfit(volmodel))
tail(fitted(volmodel))
tail(dailyvol)
summary(highmodel2 <- lm(dailyhigh2~ lag1(dailyhigh)))
tail(cbind(date, generalfit(highmodel2), lag1(dailyhigh), dailyhigh2, dailyhigh))
tail(unclass(date))
     + lag1(high5/close)
+ lag1(diff1(dailychange))
summary(m)
xyplot(m)
??lm
(close/high5)
?plot
highgivenlow(45.40)
lowgivenhigh(45.94)
tail(dailyvol,1)
highgivenlow(50.85)
lowgivenhigh(45.51)
lowgivenhigh(27.98, fndx)
lowgivenhigh(27.86,fnda)
schm  = setup("SCHM")
lowgivenhigh(51.70, schz)
lowgivenhigh(32.03, schf)
#
lowgivenhigh(52.40, scha)
